// AUTO-GENERATED by `amplify codegen` — do not edit manually.
// Run `amplify push && amplify codegen` to regenerate after schema changes.
//
// `recruitedBy` + Shop input aliases below are maintained manually when codegen lags.

export type CreatebusinessInput = {
  id?: string | null;
  name: string;
  category: string;
  description?: string | null;
  neighborhood: string;
  mapLat?: number | null;
  mapLng?: number | null;
  whatsapp: string;
  phone?: string | null;
  coverPhotoKey?: string | null;
  galleryPhotoKeys?: string[] | null;
  instagram?: string | null;
  facebook?: string | null;
  tiktok?: string | null;
  verified?: boolean | null;
  rating?: number | null;
  ownerName?: string | null;
  referralSource?: string | null;
  recruitedBy?: string | null;
  listedSince?: string | null;
  replyTime?: string | null;
};

export type UpdatebusinessInput = {
  id: string;
  name?: string | null;
  category?: string | null;
  description?: string | null;
  neighborhood?: string | null;
  mapLat?: number | null;
  mapLng?: number | null;
  whatsapp?: string | null;
  phone?: string | null;
  coverPhotoKey?: string | null;
  galleryPhotoKeys?: string[] | null;
  instagram?: string | null;
  facebook?: string | null;
  tiktok?: string | null;
  verified?: boolean | null;
  rating?: number | null;
  ownerName?: string | null;
  referralSource?: string | null;
  recruitedBy?: string | null;
  listedSince?: string | null;
  replyTime?: string | null;
};

/** Mirrors AppSync `CreateShopInput` (same shape as CreatebusinessInput in this project). */
export type CreateShopInput = CreatebusinessInput;

/** Mirrors AppSync `UpdateShopInput` (same shape as UpdatebusinessInput in this project). */
export type UpdateShopInput = UpdatebusinessInput;

export type DeletebusinessInput = {
  id: string;
};

export type CreateReviewInput = {
  id?: string | null;
  businessID: string;
  reviewerName: string;
  rating: number;
  comment: string;
  date: string;
};

export type ModelbusinessFilterInput = {
  id?: ModelIDInput | null;
  name?: ModelStringInput | null;
  category?: ModelStringInput | null;
  neighborhood?: ModelStringInput | null;
  owner?: ModelStringInput | null;
  and?: Array<ModelbusinessFilterInput | null> | null;
  or?: Array<ModelbusinessFilterInput | null> | null;
  not?: ModelbusinessFilterInput | null;
};

export type ModelIDInput = {
  ne?: string | null;
  eq?: string | null;
  le?: string | null;
  lt?: string | null;
  ge?: string | null;
  gt?: string | null;
  contains?: string | null;
  notContains?: string | null;
  between?: Array<string | null> | null;
  beginsWith?: string | null;
  attributeExists?: boolean | null;
  attributeType?: ModelAttributeTypes | null;
  size?: ModelSizeInput | null;
};

export type ModelStringInput = {
  ne?: string | null;
  eq?: string | null;
  le?: string | null;
  lt?: string | null;
  ge?: string | null;
  gt?: string | null;
  contains?: string | null;
  notContains?: string | null;
  between?: Array<string | null> | null;
  beginsWith?: string | null;
  attributeExists?: boolean | null;
  attributeType?: ModelAttributeTypes | null;
  size?: ModelSizeInput | null;
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}

export type ModelSizeInput = {
  ne?: number | null;
  eq?: number | null;
  le?: number | null;
  lt?: number | null;
  ge?: number | null;
  gt?: number | null;
  between?: Array<number | null> | null;
};
